config/routes.rb
Uploader::Application.routes.draw do
  resources :uploads

  root 'uploads#new'

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  mount_uploader :package, PackageUploader
  validates :user_name, presence: true
  validates :message, presence: true
  validates :package, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :recipient_email, presence: true,
                    format: { with: VALID_EMAIL_REGEX }
  validates :user_email, presence: true,
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to new_upload_path, notice: 'Upload was successfully created.' }

        # Tell the UserMailer to send a welcome Email after save
        UploadMailer.send_confirmation_email(@upload).deliver
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to new_upload_path, notice: 'Upload was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def confirmation
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:user_name, :user_email, :recipient_email, :message, :package)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for @upload, :html => { :multipart => true } do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :user_email %><br>
    <%= f.text_field :user_email %>
  </div>
  <div class="field">
    <%= f.label :recipient_email %><br>
    <%= f.text_field :recipient_email %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="field">
    <%= f.file_field :package %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/confirmation.html.erb
CONGRATULATIONS! UPLOAD SUCCESSFUL

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Sent To</th>
      <th>Attachment</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.user_name %></td>
        <td><%= upload.user_email %></td>
        <td><%= upload.recipient_email %></td>
        <td><%= link_to upload.package, upload.package.url %></td>
        <td><%= link_to 'Show', upload %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>Do You Want To Share A File?</h1>

<%= render 'form' %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @upload.user_name %>
  < <%= @upload.user_email %> >
</p>
<p>
  <strong>To:</strong>
  <%= @upload.recipient_email %>
</p>
<p>
  <strong>Message:</strong>
  <%= @upload.message %>
</p>
<p>
  <strong>File:</strong>
  <%= link_to @upload.package, @upload.package.url %>
</p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>